config/routes.rb
FtCampaigner::Application.routes.draw do
  resources :user_sessions, :only => [:new, :create, :destroy]
  get "user_sessions/callback"
  match 'signin', :to => 'user_sessions#new'
  match 'signout', :to => 'user_sessions#destroy'

  resource :account, :only => [:edit, :update]

  get   "synchronize/new/step_1",       :to => "synchronize#step_1"
  post  "synchronize/new/save_step_1",  :to => "synchronize#save_step_1"
  get   "synchronize/new/step_2",       :to => "synchronize#step_2"
  post  "synchronize",                  :to => 'synchronize#create'
  get   "synchronize/get_attributes"

  resources :lists, :only => [:index, :show] do
    resources :campaigns, :only => [:index, :show]
  end

  match 'home', :to => "home#index"
  root :to => 'home#index'
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :require_user_session
  before_filter :load_account
  before_filter :load_hominid
  
  def index
    @syncd_lists = find_syncd_lists
  end

  def show
    @syncd_lists = find_syncd_lists
    @current_list = @syncd_lists.find { |list| list['id'] == params[:id] }
    
    logger.debug @current_list.to_yaml
    
    @list_members = []
    @current_page = params[:page] ? params[:page].to_i : 1
    members = @hominid.list_members(params[:id], "subscribed", @current_list['date_created'], @current_page - 1, 20)
    
    info = @hominid.list_member_info(params[:id], members['data'].map{|member| member['email']})
    
    @list_members = {
      :total_records => info['total'],
      :data => info['data']
    }
  end
  
  private
  
  def load_hominid
    @hominid = Hominid::API.new(@current_account.mailchimp_key)
  end

  def find_syncd_lists
    lists = @hominid.lists
    saved_lists = @current_account.synchronize.all
    
    syncd_lists = lists['data'].find_all do |list|
      saved_lists.find { |sl| sl.mailchimp_list_id == list['id'] }
    end
    
    syncd_lists
  end

end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_list_member.html.erb
<tr>
	<td>
		<%= member['merges']['LNAME'] %>
	</td>
	<td>
		<%= member['merges']['FNAME'] %>
	</td>
	<td class="shrink">
		<%= member['email'] %>
	</td>
</tr>

app/views/lists/_list_pager.html.erb
<ul class="pager">
	<li>
	    <% if @current_page == 1 %>
	        First
	    <% else %>
		    <a href="?page=1">First</a>
		<% end %>
	</li>
	<li>
	    <% if @current_page > 1 %>
		    <a href="?page=<%= @current_page - 1 %>">Previous</a>
		<% else %>
		    Previous
		<% end %>
	</li>
	<li>
	    <% if @current_page * 20 >= @current_list['stats']['member_count'].to_i %>
	        Next
	    <% else %>
		    <a href="?page=<%= @current_page + 1 %>">Next</a>
		<% end %>
	</li>
	<li>
	    <% if @current_list['stats']['member_count'].to_i / 20 > 1 %>
	        <% last_page = (@current_list['stats']['member_count'].to_i / 20).floor %>
	        <% if last_page == @current_page %>
	            Last
	        <% else %>
		        <a href="?page=<%= last_page %>">Last</a>
		    <% end %>
		<% else %>
		    Last
		<% end %>
	</li>
	<li class="float_right">
	    <%= "#{pluralize(@current_list['stats']['member_count'].to_i, 'Record')}" %>
	</li>
	<li class="float_right">
	   <%= "Page #{@current_page}" %>
	</li>
</ul>

app/views/lists/index.html.erb
<div class="grid_16">
	<p class="mute">
		<a href="<%= home_path %>">Dashboard</a> &gt; <b>Email Lists</b>
	</p>
	<hr />
	<div class="float_right">
		<label for="email_lists_filter" class="pill">
			<%= pluralize(@syncd_lists.length, "List") %> Total
		</label>
		<select id="email_lists_filter" name="email_lists_filter" class="input_large jump_list">
			<option value="">--</option>
            <%= options_for_select(@syncd_lists.map{ |list| [list['name'], list['id'].to_s] }, params[:email_lists_filter]) %>
		</select>
	</div>
	<h2>
		Email Lists
	</h2>
	<hr />
</div>
<div class="clear"></div>
<% @syncd_lists.each do |syncd_list| %>
    <div class="grid_8">
    	<div class="box">
    	    <%= link_to "View campaigns", list_campaigns_path(syncd_list['id']), :class => 'float_right pill' %>
    		<h3>
    			<%= link_to syncd_list['name'], list_path(syncd_list['id']) %>
    		</h3>
    		<table class="horiz full">
    			<tr>
    				<td>
    					<div class="inset align_center">
    						<span class="mute">People</span>
    						<br />
    						<b><%= syncd_list['member_count'].to_i %></b>
    					</div>
    				</td>
    				<td>
    					<div class="inset align_center">
    						<span class="mute">Rating</span>
    						<br />
    						<b><%= syncd_list['list_rating'].to_i %></b>
    					</div>
    				</td>
    				<td>
    					<div class="inset align_center">
    						<span class="mute">Created</span>
    						<br />
    						<b><%= Time.parse(syncd_list['date_created']).strftime("%d %b %Y").upcase %></b>
    					</div>
    				</td>
    			</tr>
    		</table>
    	</div>
    </div>
<% end %>
<div class="clear"></div>

app/views/lists/show.html.erb
<div class="grid_16">
	<p class="mute">
		<a href="<%= home_path %>">Dashboard</a> &gt; <a href="<%= lists_path %>">Email Lists</a> &gt; <b>List</b>
	</p>
	<hr />
</div>
<div class="clear"></div>
<div class="grid_4">
	<dl class="menu">
		<dt>
			Email Lists
		</dt>
		<% @syncd_lists.each do |syncd_list| %>
    		<dd <%= "class='active'" if syncd_list['id'] == @current_list['id'] %>>
    			<%= link_to syncd_list['name'], list_path(syncd_list['id']) %>
    		</dd>
		<% end %>
	</dl>
</div>
<div class="grid_12">
	<span class="float_right pill">
		Created:
		<%= Time.parse(@current_list['date_created']).strftime("%m/%d/%Y") %>
	</span>
	<h2>
		<%= @current_list['name'] %>
	</h2>
	<div class="clear"></div>
	<%= render 'list_pager' %>
	<table class="grid">
		<thead>
			<tr>
				<th>
					Last
				</th>
				<th>
					First
				</th>
				<th class="shrink">
					Email
				</th>
			</tr>
		</thead>
		<tbody>
		    <% @list_members[:data].each do |member| %>
		        <%= render :partial => "list_member", :locals => {:member => member} %>
			<% end %>
		</tbody>
	</table>
	<%= render 'list_pager' %>
</div>
<div class="clear"></div>