config/routes.rb
FtCampaigner::Application.routes.draw do
  resources :user_sessions, :only => [:new, :create, :destroy]
  get "user_sessions/callback"
  match 'signin', :to => 'user_sessions#new'
  match 'signout', :to => 'user_sessions#destroy'

  resource :account, :only => [:edit, :update]

  get   "synchronize/new/step_1",       :to => "synchronize#step_1"
  post  "synchronize/new/save_step_1",  :to => "synchronize#save_step_1"
  get   "synchronize/new/step_2",       :to => "synchronize#step_2"
  post  "synchronize",                  :to => 'synchronize#create'
  get   "synchronize/get_attributes"

  resources :lists, :only => [:index, :show] do
    resources :campaigns, :only => [:index, :show]
  end

  match 'home', :to => "home#index"
  root :to => 'home#index'
end

app/models/synchronize.rb
class Synchronize < ActiveRecord::Base
  set_table_name "synchronize"
  
  belongs_to :account
  
  validates_presence_of :account_id
  validates_presence_of :mailchimp_list_id
  
end

app/controllers/synchronize_controller.rb
class SynchronizeController < ApplicationController
  before_filter :require_user_session
  before_filter :load_account
  
  def step_1
    store_attribute_groups(nil) unless retrieve_attribute_groups.nil?
    
    attribute_groups_url = "#{current_user_session.api_url}people/AttributeGroups.json"
    raw = current_user_session.access_token.get(attribute_groups_url)
    decoded_json = ActiveSupport::JSON.decode(raw.body)
    @attribute_groups = []
    decoded_json['attributeGroups']['attributeGroup'].each do |attribute_group|
      @attribute_groups << AttributeGroup.new(attribute_group)
    end
    
    store_attribute_groups @attribute_groups
    
    @default_attributes = []
    
    if params[:search] and params[:attribute_group_id] and params[:person_attribute_id]
      group = find_attribute_group(params[:attribute_group_id].to_i)
      
      unless group.person_attributes.blank?
        @default_attributes = group.person_attributes.sort_by{ |a| a.name }
      end
      
      @people = perform_people_search(params[:person_attribute_id], params[:page] || 1)
    end
    
  end
  
  def save_step_1
    if params[:subscribers].blank?
      flash[:error] = "At least one email is required to add to a list. The people you selected don't have an email."
      
      redirect_to synchronize_new_step_1_path
    else
      subscribers = params[:subscribers] #.uniq
      
      sub_arr = []
      
      subscribers.keys.each do |email|
        last_name = subscribers[email]['last_name']
        first_name = subscribers[email]['first_name']
        id = subscribers[email]['id']
        
        logger.debug "[SUBSCRIBER] email: #{email}, first_name: #{first_name}, last_name: #{last_name}, id: #{id}"
        
        sub_arr << {:email => email, :first_name => first_name, :last_name => last_name, :id => id}
      end
      
      session[:subscribers] = sub_arr
      
      # remove the attribute groups, we don't need them anymore
      store_attribute_groups nil
    
      redirect_to synchronize_new_step_2_path
    end
    
  end

  def step_2
    # retrieve sync from session
    hominid = Hominid::API.new(@current_account.mailchimp_key)
    @lists = hominid.lists['data']
  end
  
  def create
    subscribers = session[:subscribers]
    
    if subscribers.blank?
      flash[:error] = "Something went wrong and we could not retrieve a list of subscribers."
      redirect_to synchronize_new_step_1_path
    else
      hominid = Hominid::API.new(@current_account.mailchimp_key)
      
      lists = params[:lists]
      
      subscribers.collect! { |s| {:EMAIL => s[:email], :EMAIL_TYPE => 'html', :FNAME => s[:first_name], :LNAME => s[:last_name], :F1ID => s[:id]} }
      
      lists.each do |list|
        results = hominid.list_batch_subscribe(list, subscribers, {:double_opt_in => false, :update_existing => true})

        if results['errors'].length == 0
          # all subscribes were successful, write the record to our db
          sync = Synchronize.find_or_initialize_by_mailchimp_list_id(list)
          if sync.new_record?
            sync.account = @current_account
          else
            sync.updated_at = Time.now
          end
          
          sync.save
        else
          # TODO: Need to handle
        end
      end
      
      session[:subscribers] = nil
      
      redirect_to home_path
    end

  end
  
  def get_attributes
    group = find_attribute_group(params[:attribute_group_id].to_i)

    person_attributes = []
    
    unless group.person_attributes.blank?
      person_attributes = group.person_attributes.sort_by{ |a| a.name }
    end
    
    render :partial => "options_for_attributes", :locals => { :person_attributes => person_attributes }
  end
  
  private
  
  def store_attribute_groups(attribute_groups)
    session[:attribute_groups] = attribute_groups
  end
  
  def retrieve_attribute_groups
    session[:attribute_groups]
  end
  
  def find_attribute_group(group_id)
    @attribute_groups = retrieve_attribute_groups
    @attribute_groups.find{ |attribute_group| attribute_group.id == group_id }
  end
  
  def perform_people_search(attribute_id, page)
    @search_data = nil
    people = []
    search_url = "#{current_user_session.api_url}people/Search.json?attribute=#{attribute_id}&page=#{page}&include=communications&recordsPerPage=100"
    search_raw = current_user_session.access_token.get(search_url)
    search_json = ActiveSupport::JSON.decode(search_raw.body)

    unless search_json.nil?
      @search_data = {:has_additional_pages => search_json['results']['@additionalPages'].to_i > 0, :page => search_json['results']['@pageNumber'].to_i, :total_records => search_json['results']['@totalRecords']}
      unless search_json['results']['person'].nil?
        search_json['results']['person'].each do |person|
          new_person = Person.new(person)
          people << new_person unless new_person.email.blank?
        end
      end
    end
    
    people
  end

end

app/helpers/synchronize_helper.rb
module SynchronizeHelper
end

app/views/synchronize/_options_for_attributes.html.erb
<option value="">--</option>
<%= options_for_select(person_attributes.map{ |attribute| [attribute.name, attribute.id.to_s] }, params[:person_attribute_id]) %>

app/views/synchronize/_people.html.erb
<% if people.length > 0 %>
	<p>
		<strong>Note:</strong> The following people will be added, unless you exclude them via the <em>Remove</em> button.
	</p>
    <table id="results" class="grid">
		<thead>
        	<tr>
	            <th>
	                Last
	            </th>
	            <th>
	                First
	            </th>
	            <th>
	                Email
	            </th>
	            <th>
	                Status &gt; Sub status
	            </th>
	            <th>
	                Phone
	            </th>
	            <th class="shrink">
					&nbsp;
				</th>
	        </tr>
		</thead>
		<tbody>
    	    <% people.each do |person| %>
            <tr>
                <td>
                    <%= person.last_name %>
                    <input type="hidden" name="subscribers[<%= person.email %>][last_name]" value="<%= person.last_name %>" />
                    <input type="hidden" name="subscribers[<%= person.email %>][id]" value="<%= person.id %>" />
                </td>
                <td>
                    <%= person.casual_name %>
                    <input type="hidden" name="subscribers[<%= person.email %>][first_name]" value="<%= person.casual_name %>" />
                </td>
                <td>
            		<% unless person.email.nil? %>
                    	<%= person.email %>
            		<% else %>
            			<%= html_slug %>
            		<% end %>
                </td>
                <td>
                    <% unless person.status.nil? %>
            			<%= person.status %>
            			<%= " > #{person.sub_status}" unless person.sub_status.nil? %>
            		<% else %>
            			<%= html_slug %>
            		<% end %>
                </td>
                <td>
            		<% unless person.phone.nil? %>
                    	<%= person.phone %>
            		<% else %>
            			<%= html_slug %>
            		<% end %>
                </td>
                <td class="shrink">
            		<a href="#" class="remove">Remove</a>
            	</td>
            </tr>
	        <% end %>
		</tbody>
    </table>
    <ul class="pager">
        <li class="float_right">
            <%= @search_data[:total_records] %>
            records
        </li>
    </ul>
<% else %>
	<div class="box_error">
    	<p>
			<span class="icon_alert"></span>
			&nbsp;
			No people were found with that attribute.
	    </p>
	</div>
<% end %>

app/views/synchronize/step_1.html.erb
<div class="grid_16">
	<h2>
		<span class="mute">Synchronize &ndash;</span> Find people
	</h2>
	<%= form_tag synchronize_new_step_1_path, :method => :get do %>
		<div class="box">
			<table class="horiz">
				<tr>
					<td class="align_right">
						<label for="attribute_group">
							Attribute group
						</label>
					</td>
					<td>
						<select id="attribute_group" name="attribute_group_id" class="input_xlarge">
			                <option value="">--</option>
			                <%= options_for_select(@attribute_groups.map{ |attribute_group| [attribute_group.name, attribute_group.id.to_s] }, params[:attribute_group_id]) %>
			            </select>
					</td>
					<td class="align_right">
						<label for="person_attribute">
							Attribute
						</label>
					</td>
					<td>
						<select id="person_attribute" name="person_attribute_id" class="input_xlarge">
			                <%= render :partial => 'options_for_attributes', :locals => {:person_attributes => @default_attributes} %>
			            </select>
					</td>
					<td>
						<%= submit_tag "Find people", :disabled => params[:person_attribute_id].nil?, :name => 'search', :id => 'btn_find_people' %>
					</td>
				</tr>
			</table>
		</div>
	<% end %>
	<% if defined?(@people) %>
        <%= form_tag synchronize_new_save_step_1_path, :method => :post do %>
            <%= render :partial => 'people', :locals => {:people => @people} %>
            <% unless @people.blank? %>
				<p>
					<%= submit_tag raw("Continue to choose lists &gt;&gt;") %>
				</p>
            <% end %>
        <% end %>
	<% end %>
</div>
<script>
    $(document).ready(function() {
        $('#attribute_group').change(function() {
            APP.sync.get_attributes('<%= synchronize_get_attributes_path %>', $(this).val());
        });

        $('#person_attribute').change(function() {
            document.getElementById('btn_find_people').disabled = $(this).val().length == 0;
        });
    });
</script>

app/views/synchronize/step_2.html.erb
<div class="grid_16">
    <h2>
		<span class="mute">Synchronize &ndash;</span> Add to lists
	</h2>
    <%= form_tag synchronize_path, :method => :post do %>
        <table class="grid">
			<thead>
            	<tr>
	                <th class="shrink align_center">
						<a href="#" class="check_all">All</a>
					</th>
	                <th>
						Name
					</th>
	                <th class="align_right">
						Subscribers
					</th>
					<th class="align_right">
					    Campaigns
					</th>
	                <th class="align_right">
						Created
					</th>
	            </tr>
			</thead>
			<tbody>
	            <% @lists.each do |list| %>
	                <tr>
	                    <td class="shrink align_center">
	                        <input type="checkbox" name="lists[]" value="<%= list['id'] %>" />
	                    </td>
	                    <td>
	                        <%= list['name'] %>
	                    </td>
	                    <td class="align_right">
	                        <%= list['member_count'] || "0" %>
	                    </td>
	                    <td class="align_right">
	                        <%= list['campaign_count'] || "0" %>
	                    </td>
	                    <td class="align_right">
	                        <%= DateTime.parse(list['date_created']).strftime("%d %b %Y") %>
	                    </td>
	                </tr>
	            <% end %>
			</tbody>
        </table>
        <p>
            <%= submit_tag "Save people to list" %>
        </p>
    <% end %>
</div>