config/routes.rb
FtCampaigner::Application.routes.draw do
  resources :user_sessions, :only => [:new, :create, :destroy]
  get "user_sessions/callback"
  match 'signin', :to => 'user_sessions#new'
  match 'signout', :to => 'user_sessions#destroy'

  resource :account, :only => [:edit, :update]

  get   "synchronize/new/step_1",       :to => "synchronize#step_1"
  post  "synchronize/new/save_step_1",  :to => "synchronize#save_step_1"
  get   "synchronize/new/step_2",       :to => "synchronize#step_2"
  post  "synchronize",                  :to => 'synchronize#create'
  get   "synchronize/get_attributes"

  resources :lists, :only => [:index, :show] do
    resources :campaigns, :only => [:index, :show]
  end

  match 'home', :to => "home#index"
  root :to => 'home#index'
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_filter :require_user_session
  before_filter :load_account
  before_filter :load_hominid
  
  def index
    @current_list = @hominid.find_list_by_id params[:list_id]
    @current_page = params[:page] ? params[:page].to_i : 1
    @campaigns = []
    campaigns = @hominid.campaigns({:list_id => params[:list_id]},  @current_page - 1, 20)
    campaigns.each do |campaign|
      stats = @hominid.campaign_stats campaign['id']
      total_bounces = stats['hard_bounces'].to_i + stats['soft_bounces'].to_i
      @campaigns << {:id => campaign['id'], :title => campaign['title'], :send_time => campaign['send_time'], :emails_sent => stats['emails_sent'], :bounces => total_bounces, :spam => stats['abuse_reports'], :unsubscribes => stats['unsubscribes']}
    end
  end

  def show
    @current_list = @hominid.find_list_by_id params[:list_id]
    @campaigns = @hominid.campaigns({:list_id => params[:list_id]}, 0, 20)
    @campaign = @campaigns.find { |campaign| campaign['id'] == params[:id] }
    @stats = @hominid.campaign_stats params[:id]
    # get the members
    @list_members = []
    @current_page = params[:page] ? params[:page].to_i : 1
    members = @hominid.members(params[:list_id], "subscribed", @current_list['date_created'], @current_page - 1, 20)
    members.each do |member|
      @list_members << @hominid.member_info(params[:list_id], member['email'])
    end
    # get stats if needed
    @spam = []
    if @stats['abuse_reports'].to_i > 0
      @spam = @hominid.abuse_reports(@campaign['id'], 0, 1000)
    end
    
    @bounces = []
    if @stats['hard_bounces'].to_i + @stats['soft_bounces'].to_i > 0
      soft = @hominid.soft_bounces(@campaign['id'], 0, 15000)
      hard = @hominid.hard_bounces(@campaign['id'], 0, 15000)
      @bounces = soft.concat(hard).uniq
    end
    
    @unsubscribes = []
    if @stats['unsubscribes'].to_i > 0
      @unsubscribes = @hominid.unsubscribes(@campaign['id'], 0, 15000)
    end
  end
  
  private
  
  def load_hominid
    @hominid = Hominid::Base.new({:api_key => @current_account.mailchimp_key})
  end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper
  def include_paging_for_campaigns?
    @current_page > 1 and @campaigns.length == 20
  end
end

app/views/campaigns/index.html.erb
<div class="grid_16">
	<p class="mute">
		<a href="<%= home_path %>">Dashboard</a> &gt; <%= link_to "Email Lists", lists_path %> &gt; <b>Campaigns</b>
	</p>
	<hr />
	<div class="float_right">
		<label for="email_lists_filter" class="pill">
			<%= pluralize(@campaigns.length, 'Campaign') %> Total
		</label>
		<select id="campaigns_filter" name="campaigns_filter" class="input_large jump_list">
			<option value="">--</option>
            <%= options_for_select(@campaigns.map{ |campaign| [campaign[:title], campaign[:id].to_s] }, params[:campaigns_filter]) %>
		</select>
	</div>
	<h2>
		<span class="mute">Campaigns for:</span>
	    <%= @current_list['name'] %>
	</h2>
	<hr />
</div>
<div class="clear"></div>
<% unless @campaigns.blank? %>
    <% @campaigns.each do |campaign| %>
        <div class="grid_8">
        	<div class="box">
        	    <span class="float_right pill">
        	       <%= campaign[:emails_sent].to_i %> sent
        	    </span>
        		<h3 class="gutter_bottom_half">
        			<a href="<%= list_campaign_path(@current_list['id'], campaign[:id]) %>"><%= campaign[:title] %></a>
        		</h3>
        		<p class="mute">
        			Sent <%= Time.parse(campaign[:send_time]).strftime('%m/%d/%Y at %I:%M%p') %>
        		</p>
        		<table class="horiz full">
        			<tr>
        				<td>
        					<div class="inset align_center">
        						<span class="mute">Bounced</span>
        						<br />
        						<b><%= campaign[:bounces].to_i %></b>
        					</div>
        				</td>
        				<td>
        					<div class="inset align_center">
        						<span class="mute">Spam</span>
        						<br />
        						<b><%= campaign[:spam].to_i %></b>
        					</div>
        				</td>
        				<td>
        					<div class="inset align_center">
        						<span class="mute">Unsubscribed</span>
        						<br />
        						<b><%= campaign[:unsubscribes].to_i %></b>
        					</div>
        				</td>
        			</tr>
        		</table>
        	</div>
        </div>
    <% end %>
    <div class="clear"></div>
    <% if include_paging_for_campaigns? %>
        <div class="grid_16">
            <p>
                <% if @current_page > 1 %>
                    <a href="?page=<%= @current_page - 1 %>">Prev</a>
                <% end %>
        	    <% if @campaigns.length == 20 %>
                    <a href="?page=<%= @current_page + 1 %>">Next</a>
                <% end %>
            </p>
        </div>
        <div class="clear"></div>
    <% end %>
<% else %>
	<div class="grid_16">
		<div class="box">
	    	<p>
				<span class="icon_alert"></span>
				&nbsp;
				No campaigns exist for this email list.
			</p>
		</div>
	</div>
<% end %>

app/views/campaigns/show.html.erb
<div class="grid_16">
	<p class="mute">
		<a href="<%= home_path %>">Dashboard</a> &gt; <a href="<%= lists_path %>">Email Lists</a> &gt; <a href="<%= list_campaigns_path @current_list['id'] %>">Campaigns</a> &gt; <b>Campaign</b>
	</p>
	<hr />
</div>
<div class="clear"></div>
<div class="grid_4">
	<dl class="menu">
		<dt>
			Campaigns
		</dt>
		<% @campaigns.each do |campaign| %>
    		<dd <%= "class='active'" if campaign['id'] == params[:id] %>>
    			<a href="<%= list_campaign_path @current_list['id'], campaign['id'] %>"><%= campaign['title'] %></a>
    		</dd>
		<% end %>
	</dl>
	<dl class="menu">
		<dt>
			<span class="icon_alert float_right"></span>
			Alerts
		</dt>
		<dd>
			<span class="float_right"><%= @stats['hard_bounces'].to_i + @stats['soft_bounces'].to_i %></span> 
			<abbr title="Bounced">B</abbr>ounced
		</dd>
		<dd>
			<span class="float_right"><%= @stats['abuse_reports'].to_i %></span> 
			Marked as <abbr title="Marked as Spam">S</abbr>pam
		</dd>
		<dd>
			<span class="float_right"><%= @stats['unsubscribes'].to_i %></span> 
			<abbr title="Unsubscribed">U</abbr>nsubscribed
		</dd>
	</dl>
</div>
<div class="grid_12">
	<span class="float_right pill">
		Sent <%= Time.parse(@campaign['send_time']).strftime('%m/%d/%Y at %I:%M%p') %>
	</span>
	<h2 class="gutter_bottom_half">
		<%= @campaign['title'] %>
	</h2>
	<p class="mute">
		Sent to list: <%= @current_list['name'] %>
	</p>
	<div class="clear"></div>
	<%= render 'lists/list_pager' %>
	<table class="grid">
		<thead>
			<tr>
				<th>
					Last
				</th>
				<th>
					First
				</th>
				<th>
					Email
				</th>
				<th class="shrink align_center">
					Alerts
				</th>
			</tr>
		</thead>
		<tbody>
		    <% @list_members.each do |member| %>
    		    <tr>
                	<td>
                		<%= member['merges']['LNAME'] %>
                	</td>
                	<td>
                		<%= member['merges']['FNAME'] %>
                	</td>
                	<td>
                		<%= member['email'] %>
                	</td>
                	<td class="shrink align_center">
                	    <% if @bounces.include? member['email'] %>
						    <abbr title="Bounced">B</abbr>
						<% end %>
						<% if @spam.include? member['email'] %>
						    <abbr title="Marked as Spam">S</abbr>
						<% end %>
						<% if @unsubscribes.include? member['email'] %>
						    <abbr title="Unsubscribed">U</abbr>
						<% end %>
                	</td>
                </tr>
			<% end %>
		</tbody>
	</table>
	<%= render 'lists/list_pager' %>
</div>
<div class="clear"></div>