config/routes.rb
FtCampaigner::Application.routes.draw do
  resources :user_sessions, :only => [:new, :create, :destroy]
  get "user_sessions/callback"
  match 'signin', :to => 'user_sessions#new'
  match 'signout', :to => 'user_sessions#destroy'

  resource :account, :only => [:edit, :update]

  get   "synchronize/new/step_1",       :to => "synchronize#step_1"
  post  "synchronize/new/save_step_1",  :to => "synchronize#save_step_1"
  get   "synchronize/new/step_2",       :to => "synchronize#step_2"
  post  "synchronize",                  :to => 'synchronize#create'
  get   "synchronize/get_attributes"

  resources :lists, :only => [:index, :show] do
    resources :campaigns, :only => [:index, :show]
  end

  match 'home', :to => "home#index"
  root :to => 'home#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />	
<title>FT Campaigner</title>
<%= stylesheet_link_tag "reset.css", "960.css", "text.css", "formalize.css", "uniform.aristo.css", "util.css", "application.css", :cache => true %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
<%= javascript_include_tag "rails.js", "jquery.formalize.min.js", "jquery.uniform.min.js", "application.js", :cache => true %>
<%= csrf_meta_tag %>
</head>
<body>
<div id="wrapper">
	<div id="header">
		<div class="container_16">
			<div class="grid_5">
				<h1>
					<a href="<%= home_path %>">FT Campaigner</a>
				</h1>
			</div>
			<div class="grid_6 align_center">
				Church code: <%= @current_user_session.church_code.upcase %>
			</div>
			<div class="grid_5 align_right">
				<a href="<%= edit_account_path %>">Account</a>
				|
				<%= link_to "Sign out", signout_path %>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<div id="main">
		<div class="container_16">
			<% unless flash[:notice].nil? %>
				<div class="grid_16">
					<div class="box">
						<p>
							<%= flash[:notice] %>
						</p>
					</div>
				</div>
			<% end %>
			<%= yield %>
			<div class="clear"></div>
		</div>	
	</div>
</div>
<div id="footer">
	<div class="container_16">
		<div class="grid_8">
			&copy; <%= Time.now.strftime("%Y") %> <a href="http://www.fellowshiptech.com/" target="_blank">Fellowship Technologies, L.P.</a> All rights reserved.
		</div>
		<div class="grid_8 align_right">
			<a href="http://mailchimp.com/">MailChimp</a> is a trademark of <a href="http://rocketsciencegroup.com/">The Rocket Science Group</a>
		</div>
		<div class="clear"></div>
	</div>
</div>
</body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />	
<title>FT Campaigner</title>
<%= stylesheet_link_tag "reset.css", "960.css", "text.css", "formalize.css", "uniform.aristo.css", "util.css", "application.css", :cache => true %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
<%= javascript_include_tag "rails.js", "jquery.formalize.min.js", "jquery.uniform.min.js", "application.js", :cache => true %>
<%= csrf_meta_tag %>
</head>
<body>
	<div id="wrapper">
		<div id="header">
			<div class="container_16">
				<div class="grid_16 align_center">
					<h1>
						FT Campaigner
					</h1>
				</div>
				<div class="clear"></div>
			</div>
		</div>
		<div id="main">
			<div class="container_16">
				<%= yield %>
				<div class="clear"></div>
			</div>
		</div>
	</div>
	<div id="footer">
		<div class="container_16">
			<div class="grid_8">
				&copy; <%= Time.now.strftime("%Y") %> <a href="http://www.fellowshiptech.com/" target="_blank">Fellowship Technologies, L.P.</a> All rights reserved.
			</div>
			<div class="grid_8 align_right">
				<a href="http://mailchimp.com/">MailChimp</a> is a trademark of <a href="http://rocketsciencegroup.com/">The Rocket Science Group</a>
			</div>
			<div class="clear"></div>
		</div>
	</div>
</body>
</html>